package meteo

var WeatherCodeDescriptions = map[int]string{
	0:  "Clear sky",
	1:  "Mostly clear",
	2:  "Partly cloudy",
	3:  "Overcast",
	45: "Fog",
	48: "Depositing rime fog",
	51: "Drizzle: light intensity",
	53: "Drizzle: moderate intensity",
	55: "Drizzle: heavy intensity",
	56: "Freezing drizzle: light intensity",
	57: "Freezing drizzle: heavy intensity",
	61: "Rain: light intensity",
	63: "Rain: moderate intensity",
	65: "Rain: heavy intensity",
	66: "Freezing rain: light intensity",
	67: "Freezing rain: heavy intensity",
	71: "Snowfall: light intensity",
	73: "Snowfall: moderate intensity",
	75: "Snowfall: heavy intensity",
	77: "Snow grains",
	80: "Showers: light intensity",
	81: "Showers: moderate intensity",
	82: "Showers: heavy intensity",
	85: "Snow showers: light intensity",
	86: "Snow showers: heavy intensity",
	95: "Thunderstorm: slight or moderate",
	96: "Thunderstorm with hail: slight intensity",
	99: "Thunderstorm with hail: heavy intensity",
}
